### ISSUE TITLE
Technically spaces are allowed as identifiers

### ISSUE THREAD

**Issue by danedmunds** [mattn/go-jsonpointer#6]
Looking at https://tools.ietf.org/html/rfc6901

```
   For example, given the JSON document

   {
      "foo": ["bar", "baz"],
      "": 0,
      "a/b": 1,
      "c%d": 2,
      "e^f": 3,
      "g|h": 4,
      "i\\j": 5,
      "k\"l": 6,
      " ": 7,
      "m~n": 8
   }

   The following JSON strings evaluate to the accompanying values:

    ""           // the whole document
    "/foo"       ["bar", "baz"]
    "/foo/0"     "bar"
    "/"          0
    "/a~1b"      1
    "/c%d"       2
    "/e^f"       3
    "/g|h"       4
    "/i\\j"      5
    "/k\"l"      6
    "/ "         7
    "/m~0n"      8
```

`"/ "` yields 7

https://github.com/mattn/go-jsonpointer/blob/master/jsonpointer.go#L11
strings.TrimSpace() will remove leading and trailing spaces, the trailing spaces should probably be left in.

Maybe `strings.TrimLeftFunc(pointer, unicode.IsSpace)` should be used?

Adding the following test case to the Get tests shows the issue:
```{`{" ": 1}`, `/ `, 1.0, ``},```

I can make the change and issue a PR, just want to make sure @mattn is ok with the proposed change

**Comment by mattn** [comment]
I'm okay to change this. please.
